name: publish

on:
  push:
    branches:
      - master
      
permissions:
  contents: write     

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/
        
      - name: Publish
        run: |
          git config --global user.email "test@email.com"
          git config --global user.name "bin"
          npm version patch -m "版本更新至%s"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push
        run: |
          git push
